# Program: Constants
# Version: 0.1.0
# Author: Dr. Zulfiyor Bakhtiyorov
# Affiliations: University of Cambridge;
#   Xinjiang Institute of Ecology and Geography;
#   National Academy of Sciences of Tajikistan
# Year: 2025
# License: MIT License

# AUTOGENERATED FILE. DO NOT EDIT.
# Generated by tools/gen_edsdk_from_headers.py
from enum import IntEnum, IntFlag

# flat dict: constant name -> int value
ALL_CONSTANTS = {
    'kEdsPropID_Unknown': 0xffff,
    'kEdsPropID_ProductName': 2,
    'kEdsPropID_OwnerName': 4,
    'kEdsPropID_MakerName': 5,
    'kEdsPropID_DateTime': 6,
    'kEdsPropID_FirmwareVersion': 7,
    'kEdsPropID_BatteryLevel': 8,
    'kEdsPropID_SaveTo': 0xb,
    'kEdsPropID_CurrentStorage': 0xc,
    'kEdsPropID_CurrentFolder': 0xd,
    'kEdsPropID_BatteryQuality': 0x10,
    'kEdsPropID_BodyIDEx': 0x15,
    'kEdsPropID_HDDirectoryStructure': 0x20,
    'kEdsPropID_ImageQuality': 0x100,
    'kEdsPropID_Orientation': 0x102,
    'kEdsPropID_ICCProfile': 0x103,
    'kEdsPropID_FocusInfo': 0x104,
    'kEdsPropID_WhiteBalance': 0x106,
    'kEdsPropID_ColorTemperature': 0x107,
    'kEdsPropID_WhiteBalanceShift': 0x108,
    'kEdsPropID_ColorSpace': 0x10d,
    'kEdsPropID_PictureStyle': 0x114,
    'kEdsPropID_PictureStyleDesc': 0x115,
    'kEdsPropID_PictureStyleCaption': 0x200,
    'kEdsPropID_GPSVersionID': 0x800,
    'kEdsPropID_GPSLatitudeRef': 0x801,
    'kEdsPropID_GPSLatitude': 0x802,
    'kEdsPropID_GPSLongitudeRef': 0x803,
    'kEdsPropID_GPSLongitude': 0x804,
    'kEdsPropID_GPSAltitudeRef': 0x805,
    'kEdsPropID_GPSAltitude': 0x806,
    'kEdsPropID_GPSTimeStamp': 0x807,
    'kEdsPropID_GPSSatellites': 0x808,
    'kEdsPropID_GPSStatus': 0x809,
    'kEdsPropID_GPSMapDatum': 0x812,
    'kEdsPropID_GPSDateStamp': 0x81d,
    'kEdsPropID_AEMode': 0x400,
    'kEdsPropID_DriveMode': 0x401,
    'kEdsPropID_ISOSpeed': 0x402,
    'kEdsPropID_MeteringMode': 0x403,
    'kEdsPropID_AFMode': 0x404,
    'kEdsPropID_Av': 0x405,
    'kEdsPropID_Tv': 0x406,
    'kEdsPropID_ExposureCompensation': 0x407,
    'kEdsPropID_FocalLength': 0x409,
    'kEdsPropID_AvailableShots': 0x40a,
    'kEdsPropID_Bracket': 0x40b,
    'kEdsPropID_WhiteBalanceBracket': 0x40c,
    'kEdsPropID_LensName': 0x40d,
    'kEdsPropID_AEBracket': 0x40e,
    'kEdsPropID_FEBracket': 0x40f,
    'kEdsPropID_ISOBracket': 0x410,
    'kEdsPropID_NoiseReduction': 0x411,
    'kEdsPropID_FlashOn': 0x412,
    'kEdsPropID_RedEye': 0x413,
    'kEdsPropID_FlashMode': 0x414,
    'kEdsPropID_LensStatus': 0x416,
    'kEdsPropID_Artist': 0x418,
    'kEdsPropID_Copyright': 0x419,
    'kEdsPropID_AEModeSelect': 0x436,
    'kEdsPropID_PowerZoom_Speed': 0x444,
    'kEdsPropID_ColorFilter': 0x47f,
    'kEdsPropID_DigitalZoomSetting': 0x477,
    'kEdsPropID_AfLockState': 0x480,
    'kEdsPropID_BrightnessSetting': 0x483,
    'kEdsPropID_IBIS_HighResoShot': 0x4e0,
    'kEdsPropID_StillFileNameSetting': 0x4e1,
    'kEdsPropID_StillFileNameUserSet1': 0x4e2,
    'kEdsPropID_StillFileNameUserSet2': 0x4e3,
    'kEdsPropID_StillFolderName': 0x4e4,
    'kEdsPropID_MovieFileNameIndex': 0x4e5,
    'kEdsPropID_MovieFileNameReelNo': 0x4e6,
    'kEdsPropID_MovieFileNameClipNo': 0x4e7,
    'kEdsPropID_MovieFileNameUserDef': 0x4e8,
    'kEdsPropID_Evf_OutputDevice': 0x500,
    'kEdsPropID_Evf_Mode': 0x501,
    'kEdsPropID_Evf_WhiteBalance': 0x502,
    'kEdsPropID_Evf_ColorTemperature': 0x503,
    'kEdsPropID_Evf_DepthOfFieldPreview': 0x504,
    'kEdsPropID_Evf_Zoom': 0x507,
    'kEdsPropID_Evf_ZoomPosition': 0x508,
    'kEdsPropID_Evf_Histogram': 0x50a,
    'kEdsPropID_Evf_ImagePosition': 0x50b,
    'kEdsPropID_Evf_HistogramStatus': 0x50c,
    'kEdsPropID_Evf_AFMode': 0x50e,
    'kEdsPropID_Record': 0x510,
    'kEdsPropID_Evf_HistogramY': 0x515,
    'kEdsPropID_Evf_HistogramR': 0x516,
    'kEdsPropID_Evf_HistogramG': 0x517,
    'kEdsPropID_Evf_HistogramB': 0x518,
    'kEdsPropID_Evf_CoordinateSystem': 0x540,
    'kEdsPropID_Evf_ZoomRect': 0x541,
    'kEdsPropID_Evf_ImageClipRect': 0x545,
    'kEdsPropID_Evf_PowerZoom_CurPosition': 0x550,
    'kEdsPropID_Evf_PowerZoom_MaxPosition': 0x551,
    'kEdsPropID_Evf_PowerZoom_MinPosition': 0x552,
    'kEdsPropID_UTCTime': 0x1000016,
    'kEdsPropID_TimeZone': 0x1000017,
    'kEdsPropID_SummerTimeSetting': 0x1000018,
    'kEdsPropID_ManualWhiteBalanceData': 0x1000204,
    'kEdsPropID_TempStatus': 0x1000415,
    'kEdsPropID_MirrorLockUpState': 0x1000421,
    'kEdsPropID_FixedMovie': 0x1000422,
    'kEdsPropID_MovieParam': 0x1000423,
    'kEdsPropID_Aspect': 0x1000431,
    'kEdsPropID_ContinuousAfMode': 0x1000433,
    'kEdsPropID_MirrorUpSetting': 0x1000438,
    'kEdsPropID_MovieServoAf': 0x100043e,
    'kEdsPropID_AutoPowerOffSetting': 0x100045e,
    'kEdsPropID_AFEyeDetect': 0x1000455,
    'kEdsPropID_FocusShiftSetting': 0x1000457,
    'kEdsPropID_MovieHFRSetting': 0x100045d,
    'kEdsPropID_AFTrackingObject': 0x1000468,
    'kEdsPropID_RegisterFocusEdge': 0x100046c,
    'kEdsPropID_DriveFocusToEdge': 0x100046d,
    'kEdsPropID_FocusPosition': 0x100046e,
    'kEdsPropID_StillMovieDivideSetting': 0x1000470,
    'kEdsPropID_CardExtension': 0x1000471,
    'kEdsPropID_MovieCardExtension': 0x1000472,
    'kEdsPropID_StillCurrentMedia': 0x1000473,
    'kEdsPropID_MovieCurrentMedia': 0x1000474,
    'kEdsPropID_ApertureLockSetting': 0x1000476,
    'kEdsPropID_LensIsSetting': 0x10004c0,
    'kEdsPropID_ScreenDimmerTime': 0x10004c1,
    'kEdsPropID_ScreenOffTime': 0x10004c2,
    'kEdsPropID_ViewfinderOffTime': 0x10004c3,
    'kEdsPropID_Evf_ClickWBCoeffs': 0x1000506,
    'kEdsPropID_EVF_RollingPitching': 0x1000544,
    'kEdsPropID_Evf_VisibleRect': 0x1000546,
    'kEdsPropID_MovieRecVolume_IntMic': 0x1000489,
    'kEdsPropID_MovieRecVolume_ExtMic': 0x100048a,
    'kEdsPropID_MovieRecVolume_Acc': 0x100048b,
    'kEdsPropID_MovieParamEx': 0x11004c6,
    'kEdsPropID_SlowFastMode': 0x10004c7,
    'kEdsPropID_Flash_Firing': 0x200d,
    'kEdsPropID_Flash_Target': 0x201e,
    'kEdsPropID_DC_Zoom': 0x600,
    'kEdsPropID_DC_Strobe': 0x601,
    'kEdsPropID_LensBarrelStatus': 0x605,
    'kEdsCameraCommand_TakePicture': 0,
    'kEdsCameraCommand_ExtendShutDownTimer': 1,
    'kEdsCameraCommand_BulbStart': 2,
    'kEdsCameraCommand_BulbEnd': 3,
    'kEdsCameraCommand_DoEvfAf': 0x102,
    'kEdsCameraCommand_DriveLensEvf': 0x103,
    'kEdsCameraCommand_DoClickWBEvf': 0x104,
    'kEdsCameraCommand_MovieSelectSwON': 0x107,
    'kEdsCameraCommand_MovieSelectSwOFF': 0x108,
    'kEdsCameraCommand_PressShutterButton': 4,
    'kEdsCameraCommand_RequestRollPitchLevel': 0x109,
    'kEdsCameraCommand_DrivePowerZoom': 0x10d,
    'kEdsCameraCommand_SetRemoteShootingMode': 0x10f,
    'kEdsCameraCommand_RequestSensorCleaning': 0x112,
    'kEdsCameraCommand_SetModeDialDisable': 0x113,
    'kEdsCameraStatusCommand_UILock': 0,
    'kEdsCameraStatusCommand_UIUnLock': 1,
    'kEdsCameraStatusCommand_EnterDirectTransfer': 2,
    'kEdsCameraStatusCommand_ExitDirectTransfer': 3,
    'kEdsPropertyEvent_All': 0x100,
    'kEdsPropertyEvent_PropertyChanged': 0x101,
    'kEdsPropertyEvent_PropertyDescChanged': 0x102,
    'kEdsPropertyEvent_PropertyDescExChanged': 0x110,
    'kEdsObjectEvent_All': 0x200,
    'kEdsObjectEvent_VolumeInfoChanged': 0x201,
    'kEdsObjectEvent_VolumeUpdateItems': 0x202,
    'kEdsObjectEvent_FolderUpdateItems': 0x203,
    'kEdsObjectEvent_DirItemCreated': 0x204,
    'kEdsObjectEvent_DirItemRemoved': 0x205,
    'kEdsObjectEvent_DirItemInfoChanged': 0x206,
    'kEdsObjectEvent_DirItemContentChanged': 0x207,
    'kEdsObjectEvent_DirItemRequestTransfer': 0x208,
    'kEdsObjectEvent_DirItemRequestTransferDT': 0x209,
    'kEdsObjectEvent_DirItemCancelTransferDT': 0x20a,
    'kEdsObjectEvent_VolumeAdded': 0x20c,
    'kEdsObjectEvent_VolumeRemoved': 0x20d,
    'kEdsStateEvent_All': 0x300,
    'kEdsStateEvent_Shutdown': 0x301,
    'kEdsStateEvent_JobStatusChanged': 0x302,
    'kEdsStateEvent_WillSoonShutDown': 0x303,
    'kEdsStateEvent_ShutDownTimerUpdate': 0x304,
    'kEdsStateEvent_CaptureError': 0x305,
    'kEdsStateEvent_InternalError': 0x306,
    'kEdsStateEvent_AfResult': 0x309,
    'kEdsStateEvent_BulbExposureTime': 0x310,
    'kEdsStateEvent_PowerZoomInfoChanged': 0x311,
    'kEdsDataType_Unknown': 0,
    'kEdsDataType_Bool': 1,
    'kEdsDataType_String': 2,
    'kEdsDataType_Int8': 3,
    'kEdsDataType_UInt8': 6,
    'kEdsDataType_Int16': 4,
    'kEdsDataType_UInt16': 7,
    'kEdsDataType_Int32': 8,
    'kEdsDataType_UInt32': 9,
    'kEdsDataType_Int64': 0xa,
    'kEdsDataType_UInt64': 0xb,
    'kEdsDataType_Float': 0xc,
    'kEdsDataType_Double': 0xd,
    'kEdsDataType_ByteBlock': 0xe,
    'kEdsDataType_Rational': 0x14,
    'kEdsDataType_Point': 0x15,
    'kEdsDataType_Rect': 0x16,
    'kEdsDataType_Time': 0x17,
    'kEdsDataType_Bool_Array': 0x1e,
    'kEdsDataType_Int8_Array': 0x1f,
    'kEdsDataType_Int16_Array': 0x20,
    'kEdsDataType_Int32_Array': 0x21,
    'kEdsDataType_UInt8_Array': 0x22,
    'kEdsDataType_UInt16_Array': 0x23,
    'kEdsDataType_UInt32_Array': 0x24,
    'kEdsDataType_Rational_Array': 0x25,
    'kEdsDataType_FocusInfo': 0x65,
    'kEdsDataType_PictureStyleDesc': 0x66,
    'kEdsCameraCommand_EvfAf_OFF': 0,
    'kEdsCameraCommand_EvfAf_ON': 1,
    'kEdsCameraCommand_ShutterButton_OFF': 0,
    'kEdsCameraCommand_ShutterButton_Halfway': 1,
    'kEdsCameraCommand_ShutterButton_Completely': 3,
    'kEdsCameraCommand_ShutterButton_Halfway_NonAF': 0x10001,
    'kEdsCameraCommand_ShutterButton_Completely_NonAF': 0x10003,
    'kEdsEvfDriveLens_Near1': 1,
    'kEdsEvfDriveLens_Near2': 2,
    'kEdsEvfDriveLens_Near3': 3,
    'kEdsEvfDriveLens_Far1': 0x8001,
    'kEdsEvfDriveLens_Far2': 0x8002,
    'kEdsEvfDriveLens_Far3': 0x8003,
    'kEdsDrivePowerZoom_Stop': 0,
    'kEdsDrivePowerZoom_LimitOff_Wide': 1,
    'kEdsDrivePowerZoom_LimitOff_Tele': 2,
    'kEdsDrivePowerZoom_LimitOn_Wide': 0x11,
    'kEdsDrivePowerZoom_LimitOn_Tele': 0x12,
    'kEdsEvfDepthOfFieldPreview_OFF': 0,
    'kEdsEvfDepthOfFieldPreview_ON': 1,
    'kEdsSeek_Cur': 0,
    'kEdsSeek_Begin': 1,
    'kEdsSeek_End': 2,
    'kEdsAccess_Read': 0,
    'kEdsAccess_Write': 1,
    'kEdsAccess_ReadWrite': 2,
    'kEdsAccess_Error': 0xffffffff,
    'kEdsFileCreateDisposition_CreateNew': 0,
    'kEdsFileCreateDisposition_CreateAlways': 1,
    'kEdsFileCreateDisposition_OpenExisting': 2,
    'kEdsFileCreateDisposition_OpenAlways': 3,
    'kEdsFileCreateDisposition_TruncateExsisting': 4,
    'kEdsImageType_Unknown': 0,
    'kEdsImageType_Jpeg': 1,
    'kEdsImageType_CRW': 2,
    'kEdsImageType_RAW': 4,
    'kEdsImageType_CR2': 6,
    'kEdsImageType_HEIF': 8,
    'kEdsImageSize_Large': 0,
    'kEdsImageSize_Middle': 1,
    'kEdsImageSize_Small': 2,
    'kEdsImageSize_Middle1': 5,
    'kEdsImageSize_Middle2': 6,
    'kEdsImageSize_Small1': 0xe,
    'kEdsImageSize_Small2': 0xf,
    'kEdsImageSize_Small3': 0x10,
    'kEdsImageSize_Unknown': 0xffffffff,
    'kEdsCompressQuality_Normal': 2,
    'kEdsCompressQuality_Fine': 3,
    'kEdsCompressQuality_Lossless': 4,
    'kEdsCompressQuality_SuperFine': 5,
    'kEdsCompressQuality_Unknown': 0xffffffff,
    'EdsImageQuality_LJ': 0x10ff0f,
    'EdsImageQuality_MJ': 0x110ff0f,
    'EdsImageQuality_M1J': 0x510ff0f,
    'EdsImageQuality_M1F': 0x513ff0f,
    'EdsImageQuality_M1N': 0x512ff0f,
    'EdsImageQuality_M2J': 0x610ff0f,
    'EdsImageQuality_M2F': 0x613ff0f,
    'EdsImageQuality_M2N': 0x612ff0f,
    'EdsImageQuality_SJ': 0x210ff0f,
    'EdsImageQuality_S1J': 0xe10ff0f,
    'EdsImageQuality_S2J': 0xf10ff0f,
    'EdsImageQuality_LJF': 0x13ff0f,
    'EdsImageQuality_LJN': 0x12ff0f,
    'EdsImageQuality_MJF': 0x113ff0f,
    'EdsImageQuality_MJN': 0x112ff0f,
    'EdsImageQuality_SJF': 0x213ff0f,
    'EdsImageQuality_SJN': 0x212ff0f,
    'EdsImageQuality_S1JF': 0xe13ff0f,
    'EdsImageQuality_S1JN': 0xe12ff0f,
    'EdsImageQuality_S2JF': 0xf13ff0f,
    'EdsImageQuality_S3JF': 0x1013ff0f,
    'EdsImageQuality_LR': 0x64ff0f,
    'EdsImageQuality_LRLJF': 0x640013,
    'EdsImageQuality_LRLJN': 0x640012,
    'EdsImageQuality_LRMJF': 0x640113,
    'EdsImageQuality_LRMJN': 0x640112,
    'EdsImageQuality_LRSJF': 0x640213,
    'EdsImageQuality_LRSJN': 0x640212,
    'EdsImageQuality_LRS1JF': 0x640e13,
    'EdsImageQuality_LRS1JN': 0x640e12,
    'EdsImageQuality_LRS2JF': 0x640f13,
    'EdsImageQuality_LRS3JF': 0x641013,
    'EdsImageQuality_LRLJ': 0x640010,
    'EdsImageQuality_LRMJ': 0x640110,
    'EdsImageQuality_LRM1J': 0x640510,
    'EdsImageQuality_LRM1F': 0x640513,
    'EdsImageQuality_LRM1N': 0x640512,
    'EdsImageQuality_LRM2J': 0x640610,
    'EdsImageQuality_LRM2F': 0x640613,
    'EdsImageQuality_LRM2N': 0x640612,
    'EdsImageQuality_LRSJ': 0x640210,
    'EdsImageQuality_LRS1J': 0x640e10,
    'EdsImageQuality_LRS2J': 0x640f10,
    'EdsImageQuality_MR': 0x164ff0f,
    'EdsImageQuality_MRLJF': 0x1640013,
    'EdsImageQuality_MRLJN': 0x1640012,
    'EdsImageQuality_MRMJF': 0x1640113,
    'EdsImageQuality_MRMJN': 0x1640112,
    'EdsImageQuality_MRSJF': 0x1640213,
    'EdsImageQuality_MRSJN': 0x1640212,
    'EdsImageQuality_MRS1JF': 0x1640e13,
    'EdsImageQuality_MRS1JN': 0x1640e12,
    'EdsImageQuality_MRS2JF': 0x1640f13,
    'EdsImageQuality_MRS3JF': 0x1641013,
    'EdsImageQuality_MRLJ': 0x1640010,
    'EdsImageQuality_MRM1J': 0x1640510,
    'EdsImageQuality_MRM1F': 0x1640513,
    'EdsImageQuality_MRM1N': 0x1640512,
    'EdsImageQuality_MRM2J': 0x1640610,
    'EdsImageQuality_MRM2F': 0x1640613,
    'EdsImageQuality_MRM2N': 0x1640612,
    'EdsImageQuality_MRSJ': 0x1640210,
    'EdsImageQuality_SR': 0x264ff0f,
    'EdsImageQuality_SRLJF': 0x2640013,
    'EdsImageQuality_SRLJN': 0x2640012,
    'EdsImageQuality_SRMJF': 0x2640113,
    'EdsImageQuality_SRMJN': 0x2640112,
    'EdsImageQuality_SRSJF': 0x2640213,
    'EdsImageQuality_SRSJN': 0x2640212,
    'EdsImageQuality_SRS1JF': 0x2640e13,
    'EdsImageQuality_SRS1JN': 0x2640e12,
    'EdsImageQuality_SRS2JF': 0x2640f13,
    'EdsImageQuality_SRS3JF': 0x2641013,
    'EdsImageQuality_SRLJ': 0x2640010,
    'EdsImageQuality_SRM1J': 0x2640510,
    'EdsImageQuality_SRM1F': 0x2640513,
    'EdsImageQuality_SRM1N': 0x2640512,
    'EdsImageQuality_SRM2J': 0x2640610,
    'EdsImageQuality_SRM2F': 0x2640613,
    'EdsImageQuality_SRM2N': 0x2640612,
    'EdsImageQuality_SRSJ': 0x2640210,
    'EdsImageQuality_CR': 0x63ff0f,
    'EdsImageQuality_CRLJF': 0x630013,
    'EdsImageQuality_CRMJF': 0x630113,
    'EdsImageQuality_CRM1JF': 0x630513,
    'EdsImageQuality_CRM2JF': 0x630613,
    'EdsImageQuality_CRSJF': 0x630213,
    'EdsImageQuality_CRS1JF': 0x630e13,
    'EdsImageQuality_CRS2JF': 0x630f13,
    'EdsImageQuality_CRS3JF': 0x631013,
    'EdsImageQuality_CRLJN': 0x630012,
    'EdsImageQuality_CRMJN': 0x630112,
    'EdsImageQuality_CRM1JN': 0x630512,
    'EdsImageQuality_CRM2JN': 0x630612,
    'EdsImageQuality_CRSJN': 0x630212,
    'EdsImageQuality_CRS1JN': 0x630e12,
    'EdsImageQuality_CRLJ': 0x630010,
    'EdsImageQuality_CRMJ': 0x630110,
    'EdsImageQuality_CRM1J': 0x630510,
    'EdsImageQuality_CRM2J': 0x630610,
    'EdsImageQuality_CRSJ': 0x630210,
    'EdsImageQuality_CRS1J': 0x630e10,
    'EdsImageQuality_CRS2J': 0x630f10,
    'EdsImageQuality_HEIFL': 0x80ff0f,
    'EdsImageQuality_HEIFM': 0x180ff0f,
    'EdsImageQuality_HEIFM1': 0x580ff0f,
    'EdsImageQuality_HEIFM2': 0x680ff0f,
    'EdsImageQuality_HEIFLF': 0x83ff0f,
    'EdsImageQuality_HEIFLN': 0x82ff0f,
    'EdsImageQuality_HEIFMF': 0x183ff0f,
    'EdsImageQuality_HEIFMN': 0x182ff0f,
    'EdsImageQuality_HEIFS1': 0xe80ff0f,
    'EdsImageQuality_HEIFS1F': 0xe83ff0f,
    'EdsImageQuality_HEIFS1N': 0xe82ff0f,
    'EdsImageQuality_HEIFS2': 0xf80ff0f,
    'EdsImageQuality_HEIFS2F': 0xf83ff0f,
    'EdsImageQuality_RHEIFL': 0x640080,
    'EdsImageQuality_RHEIFLF': 0x640083,
    'EdsImageQuality_RHEIFLN': 0x640082,
    'EdsImageQuality_RHEIFM': 0x640180,
    'EdsImageQuality_RHEIFM1': 0x640580,
    'EdsImageQuality_RHEIFM2': 0x640680,
    'EdsImageQuality_RHEIFMF': 0x640183,
    'EdsImageQuality_RHEIFMN': 0x640182,
    'EdsImageQuality_RHEIFS1': 0x640e80,
    'EdsImageQuality_RHEIFS1F': 0x640e83,
    'EdsImageQuality_RHEIFS1N': 0x640e82,
    'EdsImageQuality_RHEIFS2': 0x640f80,
    'EdsImageQuality_RHEIFS2F': 0x640f83,
    'EdsImageQuality_CRHEIFL': 0x630080,
    'EdsImageQuality_CRHEIFLF': 0x630083,
    'EdsImageQuality_CRHEIFLN': 0x630082,
    'EdsImageQuality_CRHEIFM': 0x630180,
    'EdsImageQuality_CRHEIFMF': 0x630183,
    'EdsImageQuality_CRHEIFMN': 0x630182,
    'EdsImageQuality_CRHEIFM1': 0x630580,
    'EdsImageQuality_CRHEIFM2': 0x630680,
    'EdsImageQuality_CRHEIFS1': 0x630e80,
    'EdsImageQuality_CRHEIFS1F': 0x630e83,
    'EdsImageQuality_CRHEIFS1N': 0x630e82,
    'EdsImageQuality_CRHEIFS2': 0x630f80,
    'EdsImageQuality_CRHEIFS2F': 0x630f83,
    'EdsImageQuality_Unknown': 0xffffffff,
    'kEdsImageSrc_FullView': 0,
    'kEdsImageSrc_Thumbnail': 1,
    'kEdsImageSrc_Preview': 2,
    'kEdsImageSrc_RAWThumbnail': 3,
    'kEdsImageSrc_RAWFullView': 4,
    'kEdsTargetImageType_Unknown': 0,
    'kEdsTargetImageType_Jpeg': 1,
    'kEdsTargetImageType_TIFF': 7,
    'kEdsTargetImageType_TIFF16': 8,
    'kEdsTargetImageType_RGB': 9,
    'kEdsTargetImageType_RGB16': 0xa,
    'kEdsTargetImageType_DIB': 0xb,
    'kEdsProgressOption_NoReport': 0,
    'kEdsProgressOption_Done': 1,
    'kEdsProgressOption_Periodically': 2,
    'kEdsFileAttribute_Normal': 0,
    'kEdsFileAttribute_ReadOnly': 1,
    'kEdsFileAttribute_Hidden': 2,
    'kEdsFileAttribute_System': 4,
    'kEdsFileAttribute_Archive': 0x20,
    'kEdsObjectFormat_Unknown': 0,
    'kEdsObjectFormat_Jpeg': 0x3801,
    'kEdsObjectFormat_CR2': 0xb103,
    'kEdsObjectFormat_MP4': 0xb982,
    'kEdsObjectFormat_CR3': 0xb108,
    'kEdsObjectFormat_HEIF_CODE': 0xb10b,
    'kEdsBatteryLevel2_Empty': 0,
    'kEdsBatteryLevel2_Low': 9,
    'kEdsBatteryLevel2_Half': 0x31,
    'kEdsBatteryLevel2_Normal': 0x50,
    'kEdsBatteryLevel2_Hi': 0x45,
    'kEdsBatteryLevel2_Quarter': 0x13,
    'kEdsBatteryLevel2_Error': 0,
    'kEdsBatteryLevel2_BCLevel': 0,
    'kEdsBatteryLevel2_AC': 0xffffffff,
    'kEdsBatteryLevel2_Unknown': 0xfffffffe,
    'kEdsSaveTo_Camera': 1,
    'kEdsSaveTo_Host': 2,
    'kEdsSaveTo_Both': 3,
    'kEdsStorageType_Non': 0,
    'kEdsStorageType_CF': 1,
    'kEdsStorageType_SD': 2,
    'kEdsStorageType_HD': 4,
    'kEdsStorageType_CFast': 5,
    'kEdsStorageType_CFe': 7,
    'kEdsWhiteBalance_Auto': 0,
    'kEdsWhiteBalance_Daylight': 1,
    'kEdsWhiteBalance_Cloudy': 2,
    'kEdsWhiteBalance_Tungsten': 3,
    'kEdsWhiteBalance_Fluorescent': 4,
    'kEdsWhiteBalance_Strobe': 5,
    'kEdsWhiteBalance_WhitePaper': 6,
    'kEdsWhiteBalance_Shade': 8,
    'kEdsWhiteBalance_ColorTemp': 9,
    'kEdsWhiteBalance_PCSet1': 0xa,
    'kEdsWhiteBalance_PCSet2': 0xb,
    'kEdsWhiteBalance_PCSet3': 0xc,
    'kEdsWhiteBalance_WhitePaper2': 0xf,
    'kEdsWhiteBalance_WhitePaper3': 0x10,
    'kEdsWhiteBalance_WhitePaper4': 0x12,
    'kEdsWhiteBalance_WhitePaper5': 0x13,
    'kEdsWhiteBalance_PCSet4': 0x14,
    'kEdsWhiteBalance_PCSet5': 0x15,
    'kEdsWhiteBalance_AwbWhite': 0x17,
    'kEdsWhiteBalance_Click': -1,
    'kEdsWhiteBalance_Pasted': -2,
    'kEdsColorSpace_sRGB': 1,
    'kEdsColorSpace_AdobeRGB': 2,
    'kEdsColorSpace_Unknown': 0xffffffff,
    'kEdsPictureStyle_Standard': 0x81,
    'kEdsPictureStyle_Portrait': 0x82,
    'kEdsPictureStyle_Landscape': 0x83,
    'kEdsPictureStyle_Neutral': 0x84,
    'kEdsPictureStyle_Faithful': 0x85,
    'kEdsPictureStyle_Monochrome': 0x86,
    'kEdsPictureStyle_Auto': 0x87,
    'kEdsPictureStyle_FineDetail': 0x88,
    'kEdsPictureStyle_User1': 0x21,
    'kEdsPictureStyle_User2': 0x22,
    'kEdsPictureStyle_User3': 0x23,
    'kEdsPictureStyle_PC1': 0x41,
    'kEdsPictureStyle_PC2': 0x42,
    'kEdsPictureStyle_PC3': 0x43,
    'kEdsTransferOption_ByDirectTransfer': 1,
    'kEdsTransferOption_ByRelease': 2,
    'kEdsTransferOption_ToDesktop': 0x100,
    'kEdsAEMode_Program': 0,
    'kEdsAEMode_Tv': 1,
    'kEdsAEMode_Av': 2,
    'kEdsAEMode_Manual': 3,
    'kEdsAEMode_Bulb': 4,
    'kEdsAEMode_A_DEP': 5,
    'kEdsAEMode_DEP': 6,
    'kEdsAEMode_Custom': 7,
    'kEdsAEMode_Lock': 8,
    'kEdsAEMode_Green': 9,
    'kEdsAEMode_NightPortrait': 0xa,
    'kEdsAEMode_Sports': 0xb,
    'kEdsAEMode_Portrait': 0xc,
    'kEdsAEMode_Landscape': 0xd,
    'kEdsAEMode_Closeup': 0xe,
    'kEdsAEMode_FlashOff': 0xf,
    'kEdsAEMode_CreativeAuto': 0x13,
    'kEdsAEMode_Movie': 0x14,
    'kEdsAEMode_PhotoInMovie': 0x15,
    'kEdsAEMode_SceneIntelligentAuto': 0x16,
    'kEdsAEMode_SCN': 0x19,
    'kEdsAEMode_NightScenes': 0x17,
    'kEdsAEMode_BacklitScenes': 0x18,
    'kEdsAEMode_Children': 0x1a,
    'kEdsAEMode_Food': 0x1b,
    'kEdsAEMode_CandlelightPortraits': 0x1c,
    'kEdsAEMode_CreativeFilter': 0x1d,
    'kEdsAEMode_RoughMonoChrome': 0x1e,
    'kEdsAEMode_SoftFocus': 0x1f,
    'kEdsAEMode_ToyCamera': 0x20,
    'kEdsAEMode_Fisheye': 0x21,
    'kEdsAEMode_WaterColor': 0x22,
    'kEdsAEMode_Miniature': 0x23,
    'kEdsAEMode_Hdr_Standard': 0x24,
    'kEdsAEMode_Hdr_Vivid': 0x25,
    'kEdsAEMode_Hdr_Bold': 0x26,
    'kEdsAEMode_Hdr_Embossed': 0x27,
    'kEdsAEMode_Movie_Fantasy': 0x28,
    'kEdsAEMode_Movie_Old': 0x29,
    'kEdsAEMode_Movie_Memory': 0x2a,
    'kEdsAEMode_Movie_DirectMono': 0x2b,
    'kEdsAEMode_Movie_Mini': 0x2c,
    'kEdsAEMode_PanningAssist': 0x2d,
    'kEdsAEMode_GroupPhoto': 0x2e,
    'kEdsAEMode_Myself': 0x32,
    'kEdsAEMode_PlusMovieAuto': 0x33,
    'kEdsAEMode_SmoothSkin': 0x34,
    'kEdsAEMode_Panorama': 0x35,
    'kEdsAEMode_Silent': 0x36,
    'kEdsAEMode_Flexible': 0x37,
    'kEdsAEMode_OilPainting': 0x38,
    'kEdsAEMode_Fireworks': 0x39,
    'kEdsAEMode_StarPortrait': 0x3a,
    'kEdsAEMode_StarNightscape': 0x3b,
    'kEdsAEMode_StarTrails': 0x3c,
    'kEdsAEMode_StarTimelapseMovie': 0x3d,
    'kEdsAEMode_BackgroundBlur': 0x3e,
    'kEdsAEMode_VideoBlog': 0x3f,
    'kEdsAEMode_Unknown': 0xffffffff,
    'kEdsBracket_AEB': 1,
    'kEdsBracket_ISOB': 2,
    'kEdsBracket_WBB': 4,
    'kEdsBracket_FEB': 8,
    'kEdsBracket_Unknown': 0xffffffff,
    'kEdsEvfOutputDevice_TFT': 1,
    'kEdsEvfOutputDevice_PC': 2,
    'kEdsEvfOutputDevice_PC_Small': 8,
    'kEdsEvfZoom_Fit': 1,
    'kEdsEvfZoom_x5': 5,
    'kEdsEvfZoom_x6': 6,
    'kEdsEvfZoom_x10': 0xa,
    'kEdsEvfZoom_x15': 0xf,
    'Evf_AFMode_Quick': 0,
    'Evf_AFMode_Live': 1,
    'Evf_AFMode_LiveFace': 2,
    'Evf_AFMode_LiveMulti': 3,
    'Evf_AFMode_LiveZone': 4,
    'Evf_AFMode_LiveSingleExpandCross': 5,
    'Evf_AFMode_LiveSingleExpandAround': 6,
    'Evf_AFMode_LiveZoneLargeH': 7,
    'Evf_AFMode_LiveZoneLargeV': 8,
    'Evf_AFMode_LiveCatchAF': 9,
    'Evf_AFMode_LiveSpotAF': 0xa,
    'Evf_AFMode_FlexibleZone1': 0xb,
    'Evf_AFMode_FlexibleZone2': 0xc,
    'Evf_AFMode_FlexibleZone3': 0xd,
    'Evf_AFMode_WholeArea': 0xe,
    'Evf_AFMode_NoTraking_Spot': 0xf,
    'Evf_AFMode_NoTraking_1Point': 0x10,
    'Evf_AFMode_NoTraking_ExpandCross': 0x11,
    'Evf_AFMode_NoTraking_ExpandAround': 0x12,
    'kEdsStroboModeInternal': 0,
    'kEdsStroboModeExternalETTL': 1,
    'kEdsStroboModeExternalATTL': 2,
    'kEdsStroboModeExternalTTL': 3,
    'kEdsStroboModeExternalAuto': 4,
    'kEdsStroboModeExternalManual': 5,
    'kEdsStroboModeManual': 6,
    'kEdsETTL2ModeEvaluative': 0,
    'kEdsETTL2ModeAverage': 1,
    'kEdsDcStrobeAuto': 0,
    'kEdsDcStrobeOn': 1,
    'kEdsDcStrobeSlowsynchro': 2,
    'kEdsDcStrobeOff': 3,
    'kDcLensBarrelStateInner': 0,
    'kDcLensBarrelStateOuter': 1,
    'kDcRemoteShootingModeStop': 0,
    'kDcRemoteShootingModeStart': 1,
    'kEdsMirrorLockupStateDisable': 0,
    'kEdsMirrorLockupStateEnable': 1,
    'kEdsMirrorLockupStateDuringShooting': 2,
    'kEdsMirrorUpSettingOff': 0,
    'kEdsMirrorUpSettingOn': 1,
}

class EdsDataType(IntEnum):
    kEdsDataType_Unknown = 0
    kEdsDataType_Bool = 1
    kEdsDataType_String = 2
    kEdsDataType_Int8 = 3
    kEdsDataType_UInt8 = 6
    kEdsDataType_Int16 = 4
    kEdsDataType_UInt16 = 7
    kEdsDataType_Int32 = 8
    kEdsDataType_UInt32 = 9
    kEdsDataType_Int64 = 0xa
    kEdsDataType_UInt64 = 0xb
    kEdsDataType_Float = 0xc
    kEdsDataType_Double = 0xd
    kEdsDataType_ByteBlock = 0xe
    kEdsDataType_Rational = 0x14
    kEdsDataType_Point = 0x15
    kEdsDataType_Rect = 0x16
    kEdsDataType_Time = 0x17
    kEdsDataType_Bool_Array = 0x1e
    kEdsDataType_Int8_Array = 0x1f
    kEdsDataType_Int16_Array = 0x20
    kEdsDataType_Int32_Array = 0x21
    kEdsDataType_UInt8_Array = 0x22
    kEdsDataType_UInt16_Array = 0x23
    kEdsDataType_UInt32_Array = 0x24
    kEdsDataType_Rational_Array = 0x25
    kEdsDataType_FocusInfo = 0x65
    kEdsDataType_PictureStyleDesc = 0x66

class EdsEvfAf(IntEnum):
    kEdsCameraCommand_EvfAf_OFF = 0
    kEdsCameraCommand_EvfAf_ON = 1

class EdsShutterButton(IntEnum):
    kEdsCameraCommand_ShutterButton_OFF = 0
    kEdsCameraCommand_ShutterButton_Halfway = 1
    kEdsCameraCommand_ShutterButton_Completely = 3
    kEdsCameraCommand_ShutterButton_Halfway_NonAF = 0x10001
    kEdsCameraCommand_ShutterButton_Completely_NonAF = 0x10003

class EdsEvfDriveLens(IntEnum):
    kEdsEvfDriveLens_Near1 = 1
    kEdsEvfDriveLens_Near2 = 2
    kEdsEvfDriveLens_Near3 = 3
    kEdsEvfDriveLens_Far1 = 0x8001
    kEdsEvfDriveLens_Far2 = 0x8002
    kEdsEvfDriveLens_Far3 = 0x8003

class EdsDrivePowerZoom(IntEnum):
    kEdsDrivePowerZoom_Stop = 0
    kEdsDrivePowerZoom_LimitOff_Wide = 1
    kEdsDrivePowerZoom_LimitOff_Tele = 2
    kEdsDrivePowerZoom_LimitOn_Wide = 0x11
    kEdsDrivePowerZoom_LimitOn_Tele = 0x12

class EdsEvfDepthOfFieldPreview(IntEnum):
    kEdsEvfDepthOfFieldPreview_OFF = 0
    kEdsEvfDepthOfFieldPreview_ON = 1

class EdsSeekOrigin(IntEnum):
    kEdsSeek_Cur = 0
    kEdsSeek_Begin = 1
    kEdsSeek_End = 2

class EdsAccess(IntEnum):
    kEdsAccess_Read = 0
    kEdsAccess_Write = 1
    kEdsAccess_ReadWrite = 2
    kEdsAccess_Error = 0xffffffff

class EdsFileCreateDisposition(IntEnum):
    kEdsFileCreateDisposition_CreateNew = 0
    kEdsFileCreateDisposition_CreateAlways = 1
    kEdsFileCreateDisposition_OpenExisting = 2
    kEdsFileCreateDisposition_OpenAlways = 3
    kEdsFileCreateDisposition_TruncateExsisting = 4

class EdsImageType(IntEnum):
    kEdsImageType_Unknown = 0
    kEdsImageType_Jpeg = 1
    kEdsImageType_CRW = 2
    kEdsImageType_RAW = 4
    kEdsImageType_CR2 = 6
    kEdsImageType_HEIF = 8

class EdsImageSize(IntEnum):
    kEdsImageSize_Large = 0
    kEdsImageSize_Middle = 1
    kEdsImageSize_Small = 2
    kEdsImageSize_Middle1 = 5
    kEdsImageSize_Middle2 = 6
    kEdsImageSize_Small1 = 0xe
    kEdsImageSize_Small2 = 0xf
    kEdsImageSize_Small3 = 0x10
    kEdsImageSize_Unknown = 0xffffffff

class EdsCompressQuality(IntEnum):
    kEdsCompressQuality_Normal = 2
    kEdsCompressQuality_Fine = 3
    kEdsCompressQuality_Lossless = 4
    kEdsCompressQuality_SuperFine = 5
    kEdsCompressQuality_Unknown = 0xffffffff

class EdsImageQuality(IntEnum):
    EdsImageQuality_LJ = 0x10ff0f
    EdsImageQuality_MJ = 0x110ff0f
    EdsImageQuality_M1J = 0x510ff0f
    EdsImageQuality_M1F = 0x513ff0f
    EdsImageQuality_M1N = 0x512ff0f
    EdsImageQuality_M2J = 0x610ff0f
    EdsImageQuality_M2F = 0x613ff0f
    EdsImageQuality_M2N = 0x612ff0f
    EdsImageQuality_SJ = 0x210ff0f
    EdsImageQuality_S1J = 0xe10ff0f
    EdsImageQuality_S2J = 0xf10ff0f
    EdsImageQuality_LJF = 0x13ff0f
    EdsImageQuality_LJN = 0x12ff0f
    EdsImageQuality_MJF = 0x113ff0f
    EdsImageQuality_MJN = 0x112ff0f
    EdsImageQuality_SJF = 0x213ff0f
    EdsImageQuality_SJN = 0x212ff0f
    EdsImageQuality_S1JF = 0xe13ff0f
    EdsImageQuality_S1JN = 0xe12ff0f
    EdsImageQuality_S2JF = 0xf13ff0f
    EdsImageQuality_S3JF = 0x1013ff0f
    EdsImageQuality_LR = 0x64ff0f
    EdsImageQuality_LRLJF = 0x640013
    EdsImageQuality_LRLJN = 0x640012
    EdsImageQuality_LRMJF = 0x640113
    EdsImageQuality_LRMJN = 0x640112
    EdsImageQuality_LRSJF = 0x640213
    EdsImageQuality_LRSJN = 0x640212
    EdsImageQuality_LRS1JF = 0x640e13
    EdsImageQuality_LRS1JN = 0x640e12
    EdsImageQuality_LRS2JF = 0x640f13
    EdsImageQuality_LRS3JF = 0x641013
    EdsImageQuality_LRLJ = 0x640010
    EdsImageQuality_LRMJ = 0x640110
    EdsImageQuality_LRM1J = 0x640510
    EdsImageQuality_LRM1F = 0x640513
    EdsImageQuality_LRM1N = 0x640512
    EdsImageQuality_LRM2J = 0x640610
    EdsImageQuality_LRM2F = 0x640613
    EdsImageQuality_LRM2N = 0x640612
    EdsImageQuality_LRSJ = 0x640210
    EdsImageQuality_LRS1J = 0x640e10
    EdsImageQuality_LRS2J = 0x640f10
    EdsImageQuality_MR = 0x164ff0f
    EdsImageQuality_MRLJF = 0x1640013
    EdsImageQuality_MRLJN = 0x1640012
    EdsImageQuality_MRMJF = 0x1640113
    EdsImageQuality_MRMJN = 0x1640112
    EdsImageQuality_MRSJF = 0x1640213
    EdsImageQuality_MRSJN = 0x1640212
    EdsImageQuality_MRS1JF = 0x1640e13
    EdsImageQuality_MRS1JN = 0x1640e12
    EdsImageQuality_MRS2JF = 0x1640f13
    EdsImageQuality_MRS3JF = 0x1641013
    EdsImageQuality_MRLJ = 0x1640010
    EdsImageQuality_MRM1J = 0x1640510
    EdsImageQuality_MRM1F = 0x1640513
    EdsImageQuality_MRM1N = 0x1640512
    EdsImageQuality_MRM2J = 0x1640610
    EdsImageQuality_MRM2F = 0x1640613
    EdsImageQuality_MRM2N = 0x1640612
    EdsImageQuality_MRSJ = 0x1640210
    EdsImageQuality_SR = 0x264ff0f
    EdsImageQuality_SRLJF = 0x2640013
    EdsImageQuality_SRLJN = 0x2640012
    EdsImageQuality_SRMJF = 0x2640113
    EdsImageQuality_SRMJN = 0x2640112
    EdsImageQuality_SRSJF = 0x2640213
    EdsImageQuality_SRSJN = 0x2640212
    EdsImageQuality_SRS1JF = 0x2640e13
    EdsImageQuality_SRS1JN = 0x2640e12
    EdsImageQuality_SRS2JF = 0x2640f13
    EdsImageQuality_SRS3JF = 0x2641013
    EdsImageQuality_SRLJ = 0x2640010
    EdsImageQuality_SRM1J = 0x2640510
    EdsImageQuality_SRM1F = 0x2640513
    EdsImageQuality_SRM1N = 0x2640512
    EdsImageQuality_SRM2J = 0x2640610
    EdsImageQuality_SRM2F = 0x2640613
    EdsImageQuality_SRM2N = 0x2640612
    EdsImageQuality_SRSJ = 0x2640210
    EdsImageQuality_CR = 0x63ff0f
    EdsImageQuality_CRLJF = 0x630013
    EdsImageQuality_CRMJF = 0x630113
    EdsImageQuality_CRM1JF = 0x630513
    EdsImageQuality_CRM2JF = 0x630613
    EdsImageQuality_CRSJF = 0x630213
    EdsImageQuality_CRS1JF = 0x630e13
    EdsImageQuality_CRS2JF = 0x630f13
    EdsImageQuality_CRS3JF = 0x631013
    EdsImageQuality_CRLJN = 0x630012
    EdsImageQuality_CRMJN = 0x630112
    EdsImageQuality_CRM1JN = 0x630512
    EdsImageQuality_CRM2JN = 0x630612
    EdsImageQuality_CRSJN = 0x630212
    EdsImageQuality_CRS1JN = 0x630e12
    EdsImageQuality_CRLJ = 0x630010
    EdsImageQuality_CRMJ = 0x630110
    EdsImageQuality_CRM1J = 0x630510
    EdsImageQuality_CRM2J = 0x630610
    EdsImageQuality_CRSJ = 0x630210
    EdsImageQuality_CRS1J = 0x630e10
    EdsImageQuality_CRS2J = 0x630f10
    EdsImageQuality_HEIFL = 0x80ff0f
    EdsImageQuality_HEIFM = 0x180ff0f
    EdsImageQuality_HEIFM1 = 0x580ff0f
    EdsImageQuality_HEIFM2 = 0x680ff0f
    EdsImageQuality_HEIFLF = 0x83ff0f
    EdsImageQuality_HEIFLN = 0x82ff0f
    EdsImageQuality_HEIFMF = 0x183ff0f
    EdsImageQuality_HEIFMN = 0x182ff0f
    EdsImageQuality_HEIFS1 = 0xe80ff0f
    EdsImageQuality_HEIFS1F = 0xe83ff0f
    EdsImageQuality_HEIFS1N = 0xe82ff0f
    EdsImageQuality_HEIFS2 = 0xf80ff0f
    EdsImageQuality_HEIFS2F = 0xf83ff0f
    EdsImageQuality_RHEIFL = 0x640080
    EdsImageQuality_RHEIFLF = 0x640083
    EdsImageQuality_RHEIFLN = 0x640082
    EdsImageQuality_RHEIFM = 0x640180
    EdsImageQuality_RHEIFM1 = 0x640580
    EdsImageQuality_RHEIFM2 = 0x640680
    EdsImageQuality_RHEIFMF = 0x640183
    EdsImageQuality_RHEIFMN = 0x640182
    EdsImageQuality_RHEIFS1 = 0x640e80
    EdsImageQuality_RHEIFS1F = 0x640e83
    EdsImageQuality_RHEIFS1N = 0x640e82
    EdsImageQuality_RHEIFS2 = 0x640f80
    EdsImageQuality_RHEIFS2F = 0x640f83
    EdsImageQuality_CRHEIFL = 0x630080
    EdsImageQuality_CRHEIFLF = 0x630083
    EdsImageQuality_CRHEIFLN = 0x630082
    EdsImageQuality_CRHEIFM = 0x630180
    EdsImageQuality_CRHEIFMF = 0x630183
    EdsImageQuality_CRHEIFMN = 0x630182
    EdsImageQuality_CRHEIFM1 = 0x630580
    EdsImageQuality_CRHEIFM2 = 0x630680
    EdsImageQuality_CRHEIFS1 = 0x630e80
    EdsImageQuality_CRHEIFS1F = 0x630e83
    EdsImageQuality_CRHEIFS1N = 0x630e82
    EdsImageQuality_CRHEIFS2 = 0x630f80
    EdsImageQuality_CRHEIFS2F = 0x630f83
    EdsImageQuality_Unknown = 0xffffffff

class EdsImageSource(IntEnum):
    kEdsImageSrc_FullView = 0
    kEdsImageSrc_Thumbnail = 1
    kEdsImageSrc_Preview = 2
    kEdsImageSrc_RAWThumbnail = 3
    kEdsImageSrc_RAWFullView = 4

class EdsTargetImageType(IntEnum):
    kEdsTargetImageType_Unknown = 0
    kEdsTargetImageType_Jpeg = 1
    kEdsTargetImageType_TIFF = 7
    kEdsTargetImageType_TIFF16 = 8
    kEdsTargetImageType_RGB = 9
    kEdsTargetImageType_RGB16 = 0xa
    kEdsTargetImageType_DIB = 0xb

class EdsProgressOption(IntEnum):
    kEdsProgressOption_NoReport = 0
    kEdsProgressOption_Done = 1
    kEdsProgressOption_Periodically = 2

class EdsFileAttributes(IntEnum):
    kEdsFileAttribute_Normal = 0
    kEdsFileAttribute_ReadOnly = 1
    kEdsFileAttribute_Hidden = 2
    kEdsFileAttribute_System = 4
    kEdsFileAttribute_Archive = 0x20

class EdsObjectFormat(IntEnum):
    kEdsObjectFormat_Unknown = 0
    kEdsObjectFormat_Jpeg = 0x3801
    kEdsObjectFormat_CR2 = 0xb103
    kEdsObjectFormat_MP4 = 0xb982
    kEdsObjectFormat_CR3 = 0xb108
    kEdsObjectFormat_HEIF_CODE = 0xb10b

class EdsBatteryLevel2(IntEnum):
    kEdsBatteryLevel2_Empty = 0
    kEdsBatteryLevel2_Low = 9
    kEdsBatteryLevel2_Half = 0x31
    kEdsBatteryLevel2_Normal = 0x50
    kEdsBatteryLevel2_Hi = 0x45
    kEdsBatteryLevel2_Quarter = 0x13
    kEdsBatteryLevel2_Error = 0
    kEdsBatteryLevel2_BCLevel = 0
    kEdsBatteryLevel2_AC = 0xffffffff
    kEdsBatteryLevel2_Unknown = 0xfffffffe

class EdsSaveTo(IntEnum):
    kEdsSaveTo_Camera = 1
    kEdsSaveTo_Host = 2
    kEdsSaveTo_Both = 3

class EdsStorageType(IntEnum):
    kEdsStorageType_Non = 0
    kEdsStorageType_CF = 1
    kEdsStorageType_SD = 2
    kEdsStorageType_HD = 4
    kEdsStorageType_CFast = 5
    kEdsStorageType_CFe = 7

class EdsWhiteBalance(IntEnum):
    kEdsWhiteBalance_Auto = 0
    kEdsWhiteBalance_Daylight = 1
    kEdsWhiteBalance_Cloudy = 2
    kEdsWhiteBalance_Tungsten = 3
    kEdsWhiteBalance_Fluorescent = 4
    kEdsWhiteBalance_Strobe = 5
    kEdsWhiteBalance_WhitePaper = 6
    kEdsWhiteBalance_Shade = 8
    kEdsWhiteBalance_ColorTemp = 9
    kEdsWhiteBalance_PCSet1 = 0xa
    kEdsWhiteBalance_PCSet2 = 0xb
    kEdsWhiteBalance_PCSet3 = 0xc
    kEdsWhiteBalance_WhitePaper2 = 0xf
    kEdsWhiteBalance_WhitePaper3 = 0x10
    kEdsWhiteBalance_WhitePaper4 = 0x12
    kEdsWhiteBalance_WhitePaper5 = 0x13
    kEdsWhiteBalance_PCSet4 = 0x14
    kEdsWhiteBalance_PCSet5 = 0x15
    kEdsWhiteBalance_AwbWhite = 0x17
    kEdsWhiteBalance_Click = -1
    kEdsWhiteBalance_Pasted = -2

class EdsColorSpace(IntEnum):
    kEdsColorSpace_sRGB = 1
    kEdsColorSpace_AdobeRGB = 2
    kEdsColorSpace_Unknown = 0xffffffff

class EdsPictureStyle(IntEnum):
    kEdsPictureStyle_Standard = 0x81
    kEdsPictureStyle_Portrait = 0x82
    kEdsPictureStyle_Landscape = 0x83
    kEdsPictureStyle_Neutral = 0x84
    kEdsPictureStyle_Faithful = 0x85
    kEdsPictureStyle_Monochrome = 0x86
    kEdsPictureStyle_Auto = 0x87
    kEdsPictureStyle_FineDetail = 0x88
    kEdsPictureStyle_User1 = 0x21
    kEdsPictureStyle_User2 = 0x22
    kEdsPictureStyle_User3 = 0x23
    kEdsPictureStyle_PC1 = 0x41
    kEdsPictureStyle_PC2 = 0x42
    kEdsPictureStyle_PC3 = 0x43

class EdsTransferOption(IntEnum):
    kEdsTransferOption_ByDirectTransfer = 1
    kEdsTransferOption_ByRelease = 2
    kEdsTransferOption_ToDesktop = 0x100

class EdsAEMode(IntEnum):
    kEdsAEMode_Program = 0
    kEdsAEMode_Tv = 1
    kEdsAEMode_Av = 2
    kEdsAEMode_Manual = 3
    kEdsAEMode_Bulb = 4
    kEdsAEMode_A_DEP = 5
    kEdsAEMode_DEP = 6
    kEdsAEMode_Custom = 7
    kEdsAEMode_Lock = 8
    kEdsAEMode_Green = 9
    kEdsAEMode_NightPortrait = 0xa
    kEdsAEMode_Sports = 0xb
    kEdsAEMode_Portrait = 0xc
    kEdsAEMode_Landscape = 0xd
    kEdsAEMode_Closeup = 0xe
    kEdsAEMode_FlashOff = 0xf
    kEdsAEMode_CreativeAuto = 0x13
    kEdsAEMode_Movie = 0x14
    kEdsAEMode_PhotoInMovie = 0x15
    kEdsAEMode_SceneIntelligentAuto = 0x16
    kEdsAEMode_SCN = 0x19
    kEdsAEMode_NightScenes = 0x17
    kEdsAEMode_BacklitScenes = 0x18
    kEdsAEMode_Children = 0x1a
    kEdsAEMode_Food = 0x1b
    kEdsAEMode_CandlelightPortraits = 0x1c
    kEdsAEMode_CreativeFilter = 0x1d
    kEdsAEMode_RoughMonoChrome = 0x1e
    kEdsAEMode_SoftFocus = 0x1f
    kEdsAEMode_ToyCamera = 0x20
    kEdsAEMode_Fisheye = 0x21
    kEdsAEMode_WaterColor = 0x22
    kEdsAEMode_Miniature = 0x23
    kEdsAEMode_Hdr_Standard = 0x24
    kEdsAEMode_Hdr_Vivid = 0x25
    kEdsAEMode_Hdr_Bold = 0x26
    kEdsAEMode_Hdr_Embossed = 0x27
    kEdsAEMode_Movie_Fantasy = 0x28
    kEdsAEMode_Movie_Old = 0x29
    kEdsAEMode_Movie_Memory = 0x2a
    kEdsAEMode_Movie_DirectMono = 0x2b
    kEdsAEMode_Movie_Mini = 0x2c
    kEdsAEMode_PanningAssist = 0x2d
    kEdsAEMode_GroupPhoto = 0x2e
    kEdsAEMode_Myself = 0x32
    kEdsAEMode_PlusMovieAuto = 0x33
    kEdsAEMode_SmoothSkin = 0x34
    kEdsAEMode_Panorama = 0x35
    kEdsAEMode_Silent = 0x36
    kEdsAEMode_Flexible = 0x37
    kEdsAEMode_OilPainting = 0x38
    kEdsAEMode_Fireworks = 0x39
    kEdsAEMode_StarPortrait = 0x3a
    kEdsAEMode_StarNightscape = 0x3b
    kEdsAEMode_StarTrails = 0x3c
    kEdsAEMode_StarTimelapseMovie = 0x3d
    kEdsAEMode_BackgroundBlur = 0x3e
    kEdsAEMode_VideoBlog = 0x3f
    kEdsAEMode_Unknown = 0xffffffff

class EdsBracket(IntFlag):
    kEdsBracket_AEB = 1
    kEdsBracket_ISOB = 2
    kEdsBracket_WBB = 4
    kEdsBracket_FEB = 8
    kEdsBracket_Unknown = 0xffffffff

class EdsEvfOutputDevice(IntEnum):
    kEdsEvfOutputDevice_TFT = 1
    kEdsEvfOutputDevice_PC = 2
    kEdsEvfOutputDevice_PC_Small = 8

class EdsEvfZoom(IntEnum):
    kEdsEvfZoom_Fit = 1
    kEdsEvfZoom_x5 = 5
    kEdsEvfZoom_x6 = 6
    kEdsEvfZoom_x10 = 0xa
    kEdsEvfZoom_x15 = 0xf

class EdsEvfAFMode(IntEnum):
    Evf_AFMode_Quick = 0
    Evf_AFMode_Live = 1
    Evf_AFMode_LiveFace = 2
    Evf_AFMode_LiveMulti = 3
    Evf_AFMode_LiveZone = 4
    Evf_AFMode_LiveSingleExpandCross = 5
    Evf_AFMode_LiveSingleExpandAround = 6
    Evf_AFMode_LiveZoneLargeH = 7
    Evf_AFMode_LiveZoneLargeV = 8
    Evf_AFMode_LiveCatchAF = 9
    Evf_AFMode_LiveSpotAF = 0xa
    Evf_AFMode_FlexibleZone1 = 0xb
    Evf_AFMode_FlexibleZone2 = 0xc
    Evf_AFMode_FlexibleZone3 = 0xd
    Evf_AFMode_WholeArea = 0xe
    Evf_AFMode_NoTraking_Spot = 0xf
    Evf_AFMode_NoTraking_1Point = 0x10
    Evf_AFMode_NoTraking_ExpandCross = 0x11
    Evf_AFMode_NoTraking_ExpandAround = 0x12

class EdsStroboMode(IntEnum):
    kEdsStroboModeInternal = 0
    kEdsStroboModeExternalETTL = 1
    kEdsStroboModeExternalATTL = 2
    kEdsStroboModeExternalTTL = 3
    kEdsStroboModeExternalAuto = 4
    kEdsStroboModeExternalManual = 5
    kEdsStroboModeManual = 6

class EdsETTL2Mode(IntEnum):
    kEdsETTL2ModeEvaluative = 0
    kEdsETTL2ModeAverage = 1

class EdsDcStrobe(IntEnum):
    kEdsDcStrobeAuto = 0
    kEdsDcStrobeOn = 1
    kEdsDcStrobeSlowsynchro = 2
    kEdsDcStrobeOff = 3

class EdsDcLensBarrelState(IntEnum):
    kDcLensBarrelStateInner = 0
    kDcLensBarrelStateOuter = 1

class EdsDcRemoteShootingMode(IntEnum):
    kDcRemoteShootingModeStop = 0
    kDcRemoteShootingModeStart = 1

class EdsMirrorLockupState(IntEnum):
    kEdsMirrorLockupStateDisable = 0
    kEdsMirrorLockupStateEnable = 1
    kEdsMirrorLockupStateDuringShooting = 2

class EdsMirrorUpSetting(IntEnum):
    kEdsMirrorUpSettingOff = 0
    kEdsMirrorUpSettingOn = 1

# Helper classes for camera_live.py and other scripts

class PropID:
    """Property IDs for camera settings"""

    Evf_OutputDevice = 0x500
    Evf_Mode = 0x501
    ProductName = 0x02
    SaveTo = 0x0b

class CameraCommand:
    """Camera command constants"""

    TakePicture = 0
    PressShutterButton = 4
    
class EdsError:
    """EDSDK Error codes"""

    OK = 0x00000000
    UNIMPLEMENTED = 0x00000001
    INTERNAL_ERROR = 0x00000002
    MEM_ALLOC_FAILED = 0x00000003
    MEM_FREE_FAILED = 0x00000004
    OPERATION_CANCELLED = 0x00000005
    INCOMPATIBLE_VERSION = 0x00000006
    NOT_SUPPORTED = 0x00000007
    UNEXPECTED_EXCEPTION = 0x00000008
    PROTECTION_VIOLATION = 0x00000009
    MISSING_SUBCOMPONENT = 0x0000000A
    SELECTION_UNAVAILABLE = 0x0000000B
    FILE_IO_ERROR = 0x00000020
    FILE_NOT_FOUND = 0x00000022
    FILE_OPEN_ERROR = 0x00000023
    DEVICE_NOT_FOUND = 0x00000080
    DEVICE_BUSY = 0x00000081
    DEVICE_INVALID = 0x00000082
    COMM_PORT_IS_IN_USE = 0x000000C0
    SESSION_NOT_OPEN = 0x00002003
    INVALID_HANDLE = 0x00000061
    INVALID_PARAMETER = 0x00000060
    DEVICE_STAY_AWAKE = 0x000000E3
    DEVICE_NOT_LAUNCHED = 0x000000E4
    TAKE_PICTURE_AF_NG = 0x00008D01
    TAKE_PICTURE_CARD_NG = 0x00008D07
    
    @staticmethod
    def get_name(code):
        """Get error name from error code"""
        for name, value in EdsError.__dict__.items():
            if not name.startswith('_') and name != 'get_name' and value == code:
                return f"EDS_ERR_{name}"
        return f"EDS_ERR_UNKNOWN(0x{code:08X})"

# Other EDSDK defines
OTHER_DEFINES = {
    # EVF Mode
    "kEdsEvfMode_Off": 0,
    "kEdsEvfMode_On": 1,
    # EVF Output Device
    "kEdsEvfOutputDevice_TFT": 1,
    "kEdsEvfOutputDevice_PC": 2,
    "kEdsEvfOutputDevice_PC_Small": 8,
    # SaveTo
    "kEdsSaveTo_Camera": 1,
    "kEdsSaveTo_Host": 2,
    "kEdsSaveTo_Both": 3,
}

# Created by Dr. Z. Bakhtiyorov
